### ISSUE TITLE
Problematic MobileNet SSD V2 int8 model

### ISSUE THREAD

**Issue by freedomtan** [mlperf/mobile_app#55]
the [int8 model](https://github.com/mlperf/mobile_app/raw/model_repo_v0.7/tflite/ssd_mobilenet_v2_300_int8.tflite) used in the app is not a "real" quantized model. Only weights in the model are quantized. At inference, weights are converted from int8 back into fp32 to do the computation.That is, the [dynamic range quantization](https://www.tensorflow.org/lite/performance/post_training_quantization#dynamic_range_quantization) is used. I don't think it's supported by NNAPI. Please use quantization-aware trained ones, such as the quantized ones in [object detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md), or use full-integer quantization.

**Comment by terryheo** [comment]
@freedomtan thanks for filing the issue. We're working on it.

**Comment by thaink** [comment]
@freedomtan the model in http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v2_quantized_300x300_coco_2019_01_03.tar.gz is also using fake quantization as I checked. Could you recheck that?

**Comment by freedomtan** [comment]
@thaink Quantization-aware training adds Fake Quant nodes into TensorFlow graph. It uses fake quant nodes to keep track of floating values. When you convert the `tflite_graph.pb` comes with the tar file you mentioned to .tflite, there should be no fake quant nodes. E.g., I can get an`ssdv2.tflite` w/o fake quant nodes with
```
tflite_convert --graph_def_file tflite_graph.pb \
--enable_v1_converter \
--experimental_new_converter=False \
--output_file /tmp/ssdv2.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \
--inference_type=QUANTIZED_UINT8 \
--mean_values=128 --std_dev_values=128 \
--change_concat_input_ranges=false \
--allow_custom_ops
```

**Comment by thaink** [comment]
Thanks. That model has the same performance as posted in the model zoo.

**Comment by freedomtan** [comment]
because it's converted from the one in the model zoo :-)
