### ISSUE TITLE
Instruction/Example of Dummy Backend

### ISSUE THREAD

**Issue by alisoviejo** [mlperf/mobile_app#71]
Please provide instruction/example about Dummy Backend. 
For example, 
- How to build the MLPerf android mobile app with vendor run-time library (.so) 
- How to integration vendor run-time API (JNI API header file)  to the mobile app via Dummy Backend

Thanks!

**Comment by terryheo** [comment]
You can check these two PRs.

https://github.com/mlperf/mobile_app/pull/68
https://github.com/mlperf/mobile_app/pull/61
