### ISSUE TITLE
how to get the datasets for mobilebert and ade20k?

### ISSUE THREAD

**Issue by noticebo** [mlperf/mobile_app#77]
Hi. How can I get the datasets for mobilebert and ade20k mentioned in assets/task.pbtxt? thanks.

**Comment by thaink** [comment]
Hi,
Sorry for late reply. For Language Understanding and Image segmentation, it only work with dummy dataset for now. We are waiting for the accuracy implementation from mlperf/inference repo. After that is done, the app will be updated to work with the real dataset.

**Comment by noticebo** [comment]
> Hi,
> Sorry for late reply. For Language Understanding and Image segmentation, it only work with dummy dataset for now. We are waiting for the accuracy implementation from mlperf/inference repo. After that is done, the app will be updated to work with the real dataset.

ok. thanks.
