### ISSUE TITLE
does this mobile_app support signed int8 model?

### ISSUE THREAD

**Issue by noticebo** [mlperf/mobile_app#85]
I found that someone has remove the signed int8 model and add unsigned int8 tflite model. Does this mobile_app support signed int8 model? what's difference for running the signed int8 model.

**Comment by thaink** [comment]
what model are you mentioning?

**Comment by noticebo** [comment]
> what model are you mentioning?

mobilenetedgetpu_int8.tflite

**Comment by thaink** [comment]
@noticebo 
The app is actually running the signed model now https://github.com/mlperf/mobile_app/blob/master/java/org/mlperf/inference/assets/tasks.pbtxt
It can run both signed and unsigned model. However, the signed on is prefer since it is more friendly calculation for most hardwares.

**Comment by noticebo** [comment]
> @noticebo
> The app is actually running the signed model now https://github.com/mlperf/mobile_app/blob/master/java/org/mlperf/inference/assets/tasks.pbtxt
> It can run both signed and unsigned model. However, the signed on is prefer since it is more friendly calculation for most hardwares.

is there some difference to run int8 and uint8 model in operation？in other words, is there any special processing or API to run int8 model?

thanks

**Comment by thaink** [comment]
They have some differences in normalization. However, if you use the app you don't need to care about that.

**Comment by thaink** [comment]
Due to the lower accuracy. We are switching to use uint8 model now.

**Comment by thaink** [comment]
Let me close this question for now. Please reopen when you need to ask more.
