### ISSUE TITLE
how to debug the c++ source code by Android Studio

### ISSUE THREAD

**Issue by noticebo** [mlperf/mobile_app#88]
Hi,

How to debug the c++ source code by Android Studio?

thanks

**Comment by thaink** [comment]
Hi,
The C++ source code is not written by Android studio.
Are you trying to debug the c++ binary?
If you want to debug the app, run it and see the logcat  is the most straightforward way.

**Comment by noticebo** [comment]
hi,
thanks for your reply.

found it's time-consuming to rebuild the app by command:
bazel build -c opt --cxxopt='--std=c++14' \
    --fat_apk_cpu=x86,arm64-v8a,armeabi-v7a \
    //java/org/mlperf/inference:mlperf_app

what is the fast way to rebuild the app after adding one line log code?

**Comment by thaink** [comment]
Bazel has cache. So it should take less than 1 minute to rebuild.
What is your build time now.]?

**Comment by noticebo** [comment]
> Bazel has cache. So it should take less than 1 minute to rebuild.
> What is your build time now.]?

it takes me more than 2 hours to build.

**Comment by thaink** [comment]
What platform are you using? Rebuilding should be faster, it seems like your cache got deleted between runs.
Can you try another cache directory by using --output_user_root=<cache dir>?
It is documented here https://docs.bazel.build/versions/master/output_directories.html

**Comment by noticebo** [comment]
> What platform are you using? Rebuilding should be faster, it seems like your cache got deleted between runs.
> Can you try another cache directory by using --output_user_root=?
> It is documented here https://docs.bazel.build/versions/master/output_directories.html

ok. thanks.
