### ISSUE TITLE
what is the motivation for testing of number of threads?

### ISSUE THREAD

**Issue by noticebo** [mlperf/mobile_app#91]
hi,

what is the motivation for testing of number of threads? it seems the feature only works for CPU, right? What is the mechanism for setting threadnum for interpreter. thank you,

**Comment by thaink** [comment]
You are right, it only work on CPU. 
If you are writing the C++ code you can set the number of thread by:
interpreter_->SetNumThreads(num_threads);

**Comment by noticebo** [comment]
> You are right, it only work on CPU.
> If you are writing the C++ code you can set the number of thread by:
> interpreter_->SetNumThreads(num_threads);

Hi thaink,

thanks for you reply.
BTW, I would like to know details about the implementation of interpreter threading. Is this feature relating to Conv&FC computing? Could you please show me the exact path of code on TFLite framework? thanks.

**Comment by thaink** [comment]
hi,
The multithreaded conv implementation is here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/optimized/multithreaded_conv.h
interally, i think it use Eigen http://eigen.tuxfamily.org/index.php?title=Main_Page

**Comment by noticebo** [comment]
> hi,
> The multithreaded conv implementation is here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/optimized/multithreaded_conv.h
> interally, i think it use Eigen http://eigen.tuxfamily.org/index.php?title=Main_Page

got it. Besides, I noticed that when setting threadnum=4, the model on CPU has the best performance and confused that when setting threadnum > 4, the inference time will increase. do you have any comment about this phenomenon?

**Comment by thaink** [comment]
We also had the same observation. Most mobile CPUs have 4 big cores, so if the number of thread is set to more than 4, the small cores are also being used. I think the performance is worse since the big cores also need wait for the small ones before continuing.

**Comment by noticebo** [comment]
thanks. 
It seems the default number thread for the tflite framework implementation is also 4 when no user setting thread number, right?

**Comment by thaink** [comment]
In the app and binary I set the default to 4.
In TFLite itself, if the num of threads is not set, it let Eigen determine by itself.
